# This is the configuration used to check the rubocop source code.
# For list of cops 'https://github.com/bbatsov/rubocop/tree/master/config'


AllCops:
  Exclude:
    - 'config/**/*'
    - 'app/main/config/**/*'
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
    - 'bin/*'
    - 'db/**/*'
    - 'lib/onboard/sentence_splitter.rb'
    - 'lib/onboard/eu_sentence_read.rb'
    - 'test/test_helper.rb'
    - 'test/lib/content/retrieve_ipa_test.rb'
    - 'test/lib/program/setup_map_test.rb'
    - 'test/lib/onboard/retrieve_ipa_test.rb'
    - 'test/lib/onboard/wiktionary_manager_test.rb'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
